baseURL = ''
defaultContentLanguage = "fr"
defaultContentLanguageInSubdir = false
enableInlineShortcodes = true
removePathAccents = true
title = 'Social Inclusion - Digital Accessibility'

theme = ["higo","fromago","repogo","sligo","frago"]

[Params]
favicon = true

[outputformats]
  _merge = 'deep'
[cascade]
  _merge = 'deep'
[module]
  _merge = 'none'


[pagination]
  disableAliases = false
  pagerSize = 20
  path = 'page'

[markup]
  [markup.tableOfContents]
    endLevel = 6
    ordered = false
    startLevel = 2

[menus]
[[menus.main]]
    identifier = "assessment"
    name = "Assessment"
    url = "/assessment/"
    weight = 1
[[menus.main]]
    identifier = "publication"
    name = "Publications"
    url = "/publication/"
    weight = 10
[[menus.main]]
    identifier = "partnership"
    name = "Partnership"
    url = "/partnership/"
    weight = 100
[[menus.main]]
    identifier = "dashboard"
    name = "Dashboard"
    url = "/audits/"
    weight = 1000

[languages]
  [languages.fr]
    languageCode = "fr"
    languageName = "Français"
    weight = 1
    title = "Publication de contenu"
  [languages.en]
    languageCode = "en"
    languageName = "English"
    weight = 2
    title = "Content Publishing"
