title = 'Social Inclusion - Digital Accessibility'

theme = ["higo","fromago","repogo","sligo","resugo","frago"]

[menus]
[[menus.main]]
    identifier = "assessment"
    name = "Assessment"
    url = "/assessment/"
    weight = 1
[[menus.main]]
    identifier = "publication"
    name = "Publications"
    url = "/publication/"
    weight = 10
[[menus.main]]
    identifier = "partnership"
    name = "Partnership"
    url = "/partnership/"
    weight = 100
[[menus.main]]
    identifier = "dashboard"
    name = "Dashboard"
    url = "/audits/"
    weight = 1000

[languages]
  [languages.fr]
    languageCode = "fr"
    languageName = "Français"
    weight = 1
    title = "Publication de contenu"
  [languages.en]
    languageCode = "en"
    languageName = "English"
    weight = 2
    title = "Content Publishing"
